const ALGORITHMS = {
  PSO: "PSO",
  GA: "GA",
  SA: "SA"
};

const POPULATION_BASED_ALGORITHMS = [ALGORITHMS.PSO, ALGORITHMS.GA]

const FUNCTIONS = {
  FF_SPHERE: "FF_Sphere",
  FF_RASTRIGIN: "FF_Rastrigin",
  FF_SCHWEFEL: "FF_Schwefel",
  FF_ACKLEY: "FF_Ackley",
  FF_EGGHOLDER: "FF_Eggholder",
  FF_2D: "FF_2D"
};

const SELECTION_FUNCTIONS = {
  ROULETTE: "Roulette",
  TOURNAMENT: "Tournament"
};

module.exports = {ALGORITHMS, POPULATION_BASED_ALGORITHMS, FUNCTIONS, SELECTION_FUNCTIONS}